Rails.application.config.assets.precompile += %w(
  bootstrap.min.js
  waves.min.css
  menu.css
  style.css
  notis.css
  metisMenu.min.js
  jquery.flot
  jquery.flot.tooltip.min
  jquery.flot.resize
  jquery.flot.pie
  pace.min
  waves.min
  custom.js
  tables.coffee
  offers.css
  offers.coffee
  outletForm.js
  input-mask/jquery.inputmask.bundle.min.js
  grid.js
  sheet.js
  vanilla-masker.min.js
  inputMasks.js
)
