# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36050d43eda060530efc765bb6e933f505cd6c963b1ecf6dec42760ff5c76386d3bd0e108e526590341f3960d1423da2a2fccb3319efa85b745c7ae8e4c32f51

test:
  secret_key_base: 366d0be11d0bdff6b7069e4446568dacc08a80342bbc6579b7549791a1f974d9550a8d45615448d16b529518e29cf5da584b27a40f948677c8ad819f8eabecdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
